version: '3.8'
services:
  mongodb:
    image: mongo:5.0
    container_name: eco-ride-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: eco-ride

  redis:
    image: redis:6.2-alpine
    container_name: eco-ride-redis
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: eco-ride-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/eco-ride
      - REDIS_URL=redis://redis:6379

volumes:
  mongo_data: